const API = 'https://api.cloudflare.com/client/v4/' +
  'zones/6e478d3d79237d7a94595b6b3e877ec7/';
const SUBDOMAINS = [
  {
    domain: 'ip',
    key: '', // A SHA256 private key generated by you
    id: '', // ID of the subdomain entry on Cloudflare
  },
];

const AUTH = { // Your Cloudflare API authentication data
    email: '',
    key: ''
}

addEventListener('fetch', function(event) {
  event.respondWith(
    handleRequest(event.request).catch(handleError)
  );
});

async function handleRequest(request) {
  if (!request.headers.has('X-Auth')){
    return new Response(null, {
      status: 400
    });
  }

  const key = await sha256(request.headers.get('X-Auth'));
  const sub = SUBDOMAINS.find(s => s.key === key);
  if (!sub) {
    return new Response(null, {
      status: 400
    });
  }

  const ip = request.headers.get('CF-Connecting-IP');
  await updateIp(sub.domain, sub.id, ip);

  return new Response('ok ' + sub.domain, {
    headers: {
      'Content-Type': 'text/plain; charset=UTF-8'
    }
  });
}

function handleError(error) {
  console.error('Uncaught error:', error)

  const { stack } = error
  return new Response(stack || error, {
    status: 500,
    headers: {
      'Content-Type': 'text/plain;charset=UTF-8'
    }
  })
}

async function updateIp(sub, id, ip) {
  await fetch(API + 'dns_records/' + id, {
    method: 'PUT',
    headers: {
      'X-Auth-Email': auth.email,
      'X-Auth-Key': auth.key,
      'Content-type': 'application/json',
    },
    body: JSON.stringify({
      'type': 'A',
      'name': sub,
      'content': ip,
    }),
  });
}

function buf2hex(buffer) {
  return [...new Uint8Array(buffer)].map(
    x => x.toString(16).padStart(2, '0')
  ).join('');
}

async function sha256(data) {
  return buf2hex(await crypto.subtle.digest(
    'SHA-256',
    new TextEncoder().encode(data)
  ));
}